export const COLORS = {
    purpleLight: '#8D7BAF',
    purpleMekabel: '#6B4FB2',
    purpleNotnei: '#7B7BDB',
    lightPurple: '#EDEFFF',
    lightYellow: '#FFF7CB',
    textFont: '#474B4E',
    secondaryText: '#848487',
    system: '#F0F0F0',
    disable: '#E8ECF0',
    text: '#323233',
    subText: '#A5A5A5',
    background: '#F9F9FC',
    white: '#fff',
    black: '#000',
    error: '#E54C6B',
    blue: '#396BEE',
    light: '#8D7BAF',
    transparent: 'transparent',
    light2: '#F0F0F0',
  };
  